name: Build Repository on Push

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  
env:
  PROJECT: 'DotNetLibrary'
  RELEASE_NAME: 'DotNetLibrary'

jobs:    
  pack:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        project: [ Core, Client, Server ]
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Git Fetch
      run: git fetch --prune --unshallow
    
    - name: Setup .NET (6.0.x, 7.0.x)
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
        dotnet-quality: preview
        
    - name: Set Release Name ${{ matrix.project }}
      if: ${{ matrix.project != 'Core' }}
      uses: allenevans/set-env@v2.0.0
      with:
        RELEASE_NAME: ${{ env.PROJECT }}.${{ matrix.project }}
        
    - name: Build ${{ env.RELEASE_NAME }}
      run: dotnet build -c Release
